pluginId=pano-plugin-market
pluginName=Market
pluginDescription=Flexible plugin that lets you easily list, manage, and sell products on your website.
pluginPanoVersion=local-build
pluginClass=com.panomc.plugins.market.MarketPlugin
pluginDeveloper=Pano
pluginLicense=MIT
pluginSourceUrl=https://github.com/PanoMC/pano-plugin-market
pluginDependencies=
pluginRequires=

pf4jVersion=3.13.0
vertxVersion=5.0.1
gsonVersion=2.13.2
handlebarsVersion=4.4.0
springContextVersion=5.3.39
organization=panomc
panoVersion=1.0.0-alpha.539
