// Locale keys required by 04 §9 (permissions) and §10 (activity-log types).
const crud = (verbs, subjects) => subjects.flatMap((s) => verbs.map((v) => `${v}_MARKET_${s}`));
const CRUD = ['CREATED', 'UPDATED', 'DELETED'];

export const PERMISSION_KEYS = [
  'MANAGE_MARKET',
  'MANAGE_MARKET_CATALOG',
  'VIEW_MARKET_ORDERS',
  'MANAGE_MARKET_ORDERS',
  'MANAGE_MARKET_PAYMENTS',
  'MANAGE_MARKET_DISCOUNTS',
  'MANAGE_MARKET_SETTINGS',
  'VIEW_MARKET_STATS',
];

export const ACTIVITY_LOG_TYPES = [
  ...crud(CRUD, [
    'CATEGORY',
    'PRODUCT',
    'COMPARISON',
    'COUPON',
    'CREATOR_CODE',
    'DISCOUNT',
    'GIFT',
  ]),
  'SORTED_MARKET_CATEGORIES',
  'UPDATED_MARKET_SETTINGS',
  'UPDATED_MARKET_PAYMENT_METHOD',
  'REVEALED_MARKET_PAYMENT_SECRET',
  'UPDATED_MARKET_ORDER_STATUS',
  'UPDATED_MARKET_ORDER_EXCHANGE_RATE',
  'REFRESHED_EXCHANGE_RATE',
  // catalogue
  'UPDATED_MARKET_PRODUCT_STOCK',
  'IMPORTED_MARKET_CATALOG',
  ...crud(CRUD, ['GOAL']),
  // orders
  'CREATED_MARKET_ORDER',
  'CANCELLED_MARKET_ORDER',
  'REVIEWED_MARKET_ORDER',
  'APPROVED_MARKET_BANK_TRANSFER',
  'REJECTED_MARKET_BANK_TRANSFER',
  'UPDATED_MARKET_ORDER_NOTE',
  'UPDATED_MARKET_ORDER_SHIPPING_ADDRESS',
  'ANONYMIZED_MARKET_ORDER',
  'EXPORTED_MARKET_ORDERS',
  'RESENT_MARKET_ORDER_MAIL',
  'RETRIED_MARKET_MAIL',
  'REGENERATED_MARKET_INVOICE',
  // money
  'REFUNDED_MARKET_ORDER',
  'RETRIED_MARKET_REFUND',
  'CANCELLED_MARKET_REFUND',
  'OPENED_MARKET_DISPUTE',
  'UPDATED_MARKET_DISPUTE',
  'GRANTED_MARKET_CREDITS',
  'REVOKED_MARKET_CREDITS',
  'CREATED_MARKET_CREATOR_PAYOUT',
  'CANCELLED_MARKET_CREATOR_PAYOUT',
  'CANCELLED_MARKET_SUBSCRIPTION',
  'RETRIED_MARKET_SUBSCRIPTION_CHARGE',
  'REPLAYED_MARKET_PAYMENT_EVENT',
  // in game
  'GRANTED_MARKET_CREDITS_INGAME',
  'REVOKED_MARKET_CREDITS_INGAME',
  'SET_MARKET_CREDITS_INGAME',
  'GRANTED_MARKET_PRODUCT_INGAME',
  // fulfilment
  'RERAN_MARKET_DELIVERY',
  'RAN_MARKET_CHARGEBACK_ACTIONS',
  'RETRIED_MARKET_DELIVERY',
  'CANCELLED_MARKET_DELIVERY',
  'REVOKED_MARKET_ORDER',
  'CREATED_MARKET_SHIPMENT',
  'UPDATED_MARKET_SHIPMENT',
  'CANCELLED_MARKET_SHIPMENT',
  'CREATED_MARKET_BLOCK',
  'DELETED_MARKET_BLOCK',
  // settings
  'UPDATED_MARKET_CURRENCIES',
  'UPDATED_MARKET_LEGAL_TEXT',
  'TOGGLED_MARKET_PAYMENT_METHOD',
  'SORTED_MARKET_PAYMENT_METHODS',
  'RAN_MARKET_PROVIDER_ACTION',
  'FAILED_MARKET_SECRET_REVEAL',
  'UPDATED_MARKET_INVOICE_SEQUENCE',
  'UPDATED_MARKET_SERVER_SETTINGS',
  'SENT_MARKET_TEST_MAIL',
  ...crud(CRUD, ['SHIPPING_ZONE', 'SHIPPING_METHOD']),
  'UPDATED_MARKET_SHIPPING_CARRIER',
  'TOGGLED_MARKET_SHIPPING_CARRIER',
  'REVEALED_MARKET_SHIPPING_SECRET',
  ...crud(CRUD, ['WEBHOOK']),
  'TESTED_MARKET_WEBHOOK',
  'REDELIVERED_MARKET_WEBHOOK',
];

export const pascal = (snake) =>
  snake
    .toLowerCase()
    .split('_')
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
